services:
  postgres:
    container_name: PetHouseDockerContainer
    image: postgres
    environment:
      POSTGRES_DB: PetHouseDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always
  seq:
    container_name: PetHouseLogs
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    restart: always

volumes:
  postgres:

