services:
  postgres:
    container_name: PetHouseDockerContainer_petHouse
    image: postgres
    environment:
      POSTGRES_DB: PetHouseDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always

  pgadmin:
    container_name: pgadmin_container_petHouse
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_SERVER_1_HOST: postgres
      PGADMIN_SERVER_1_PORT: 5434
      PGADMIN_SERVER_1_USERNAME: postgres
      PGADMIN_SERVER_1_PASSWORD: 123456
      PGADMIN_SERVER_1_DBNAME: PetHouseDb
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  seq:
    container_name: PetHouseLogs_petHouse
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    restart: always

  minio:
    container_name: minio_petHouse
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always

volumes:
  postgres:
  pgadmin:
  minio_data:
    driver: local